# Generated by Django 5.2.6 on 2025-09-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyComplaint',
        ),
    ]
